name: Dependabot Auto Merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ahmadnassri/action-dependabot-auto-merge@master
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
